giantswarm/mayu

- cache/usr/share/oem/cloud-config.yml
- config.go
- templates/last_stage_cloudconfig.yaml
The first stage cloud-config was compiled into the image (this is done in the `cache/coreos_production_pxe_image.cpio.gz` make target) and I forgot to add it to the repo.
Also the Yochu version check in the last stage cloud-config still wasn't correct. 
I was able to spin up a cluster with this fixes.
> Cloudconfig fixes

- pxemanager.go
Make sure that while multiple servers are installing dns is updated atomically.
Stumbled upon this during a test where Mayu reported a nil pointer exception within this function.
> lock dns updates

- docs/README.md
- docs/compiling.md
- docs/configuration.md
- docs/flags.md
- docs/inside.md
- docs/mayuctl.md
- docs/release.md
- docs/running.md
- docs/security.md
- docs/templates.md
- renamed `bootxectl.md` to `mayuctl.md`
- Wrote Mayu when the entire software is referenced. Wrote `mayu`
when the specific binary is meant.
- Set syntax highlighting helpers (“nohighlight” for all shell, mixed
and plain text output)
- Applied strict headline hierarchy
- Removed — (horizontal lines), since headlines should be enough to
structure the content
- Set file names in headlines in backticks (literals)
- Removed superfluous empty lines
- very few language modifications
RFR @puja108
> Docs cleanup iteration

- Makefile
- README.md
- config.go
- config.yaml.dist
- pxemanager.go
- scripts/fetch-mayu-assets
removed etcd, fleet, docker and yochu from release. you can fetch your own versions now independently from a release.
* smaller docker image
* multiple versions in parallel
Similar to #33
> Etcd, fleet, docker independent from releases

- mayuctl/list.go
Added two new parameters:
Omit the legend of the output
```
mayuctl list --no-legend
```
Change the fields in the output
```
mayuctl list --fields=machined,profile,coreos,yochu
```
The output will be sorted (currently only comparing the full string of each line)
> change fields in mayuctl list and sort the output

- templates/examples/bonding.yaml
- templates/last_stage_cloudconfig.yaml
Mask the service locksmithd to avoid weird behaviors and states.
```
-- Reboot --
Mar 04 09:35:54 00002c1a00dd1eda systemd[1]: Started Cluster reboot manager.
Mar 04 09:35:54 00002c1a00dd1eda systemd[1]: Starting Cluster reboot manager...
Mar 04 09:35:54 00002c1a00dd1eda locksmithd[692]: Cannot get update engine status: The name com.coreos.update1 was not provided by any .service files
Mar 04 09:35:54 00002c1a00dd1eda systemd[1]: locksmithd.service: main process exited, code=exited, status=1/FAILURE
Mar 04 09:35:54 00002c1a00dd1eda systemd[1]: Unit locksmithd.service entered failed state.
Mar 04 09:35:54 00002c1a00dd1eda systemd[1]: locksmithd.service failed.
Mar 04 09:35:55 00002c1a00dd1eda systemd[1]: locksmithd.service holdoff time over, scheduling restart.
Mar 04 09:35:55 …
```
> Masking locksmithd service

- README.md
- config.yaml.dist
- docs/configuration.md
- docs/mayuctl.md
- hostmgr/host.go
- mayuctl/status.go
- pxemgr/config.go
- pxemgr/ipxe_handlers.go
- templates/examples/bonding.yaml
- templates/last_stage_cloudconfig.yaml
We should be able to use the `FLEET_DISABLE_ENGINE` to specify whether our fleet nodes could be elected or not as fleet leaders (or in other words to work as engines). This property should depend on a property specified in the `config.yaml`, `disable_engine`.
State: Testing it in my local cluster
> Add disable_engine property to specify fleet disable engine value

- config.yaml.dist
- pxemgr/config.go
- pxemgr/ipxe_handlers.go
We can now define the CoreOS version in the profiles `config.yaml`.
ping @teemow
> Define the coreOS version in the profiles

- config.yaml.dist
- pxemgr/config.go
- pxemgr/ipxe_handlers.go
- pxemgr/pxemanager.go
the default coreos version has been hardcoded before. this version is used to bootstrap machines (first boot) and needs to be defined.
> add default coreos version to config.yaml

- Makefile
- docs/README.md
- docs/qemu.md
- pxemgr/ipxe_handlers.go
- scripts/fetch-coreos-qemu-image
We are using KVM to start CoreOS in CoreOS. To make such installations self-contained Mayu is now able to provide the QEMU images too.
> add fetching of qemu images to run coreos in coreos

- hostmgr/cluster.go
- main.go
- pxemgr/etcd_discovery_handlers.go
- pxemgr/pxemanager.go
Gracefully handle existing etcd discovery url in `cluster.json`. 
* If `--etcd-discovery` and the old `EtcdDiscoveryURL` are the same discovery -> token is stored and `EtcdDiscoveryURL` is removed
* If the internal etcd discovery is used (which is the default) then the token is stored in etcd and the `EtcdDiscoveryURL` is removed. Note: the machine/member data is not transferred. Also existing machines will still have the old discovery URL in their cloud-config.
* If `--etcd-discovery` and the old `EtcdDiscoveryURL`do not match startup is refused and needs to be fixed manually.
> Convert deprecated EtcdDiscoveryURL to new DefaultEtcdClusterToken

- glide.lock
- vendor/github.com/golang/glog/README
- vendor/github.com/golang/glog/glog.go
Fix https://github.com/giantswarm/mayu/issues/75
We should think about using another logging solution: log15 or something else
Problem fixed:
```
mayu_1      | E1028 13:25:15.262408       1 dnsmasq.go:75] signal: killed
mayu_1      | I1028 13:25:15.288934       1 dnsmasq.go:57] 
mayu_1      | I1028 13:25:15.289011       1 dnsmasq.go:57] dnsmasq: failed to create listening socket for 10.0.3.251: Cannot assign requested address
etcd_1      | 2016-10-28 13:25:15.122069 I | etcdserver: restarting member bf9071f4639c75cc in cluster 7bdc11851051b492 at commit index 9807
etcd_1      | 2016-10-28 13:25:15.125842 I | raft: bf9071f4639c75cc became follower at term 3
etcd_1      | 2016-10-28 13:25:15.125866 I | raft: newRaft bf9071f4639c75cc [peers: [], term: 3, commit: 9807, applied: 0, lastindex: …
```
> Regression of glog version to fix noisy logging issue

- hostmgr/cluster.go
- main.go
- pxemgr/etcd_discovery_handlers.go
- pxemgr/pxemanager.go
Mayu only supports connecting to etcd via unsecure `http`
In `vodafone setup` we will be using TLS for `etcd` and since certs will be generated via `vault` we also need `mayu` support for custom root CA when connecting to `etcd`.
Changes:
1. removed hardcoded `http` protocol prefix for etcd endpoint 
2. added support for custom root CA when connecting to `etcd`. (new param `--etcd-cafile`)
ping @giantswarm/team-positive @teemow
> Etcdendpoint https support

- Dockerfile
apparently  `mayu` needs `git` for running the gtihub updates.
> add git to docker image

- Dockerfile
We built mayu  from `alpine:3.4` and our quay security scan reports 4 high risk vulnerabilities and because we care I wanted to solve this.
Current latest version for alpine is `3.6`
lets switch to `latest` alpine image, so each time we build mayu we have security update
> updaye-mayu-docker-base

- templates/first_stage_script.sh
Machine id has to readable by `systemd-networkd` which runs under `systemd-networkd` user.
> machine-id file permissions

- config.yaml.dist
- docs/configuration.md
- pxemgr/config.go
- template_snippets/cloudconfig/net_bond.yaml
- template_snippets/cloudconfig/net_bridge.yaml
- template_snippets/cloudconfig/net_singlenic.yaml
- template_snippets/ignition/net_bond.yaml
- template_snippets/ignition/net_singlenic.yaml
currently, we were using `{{.ClusterNetwork.Router}}` as gateway, but that is gateway for PXE network and if the network is different then it won't work, so we need another value for gateway.
* added `SubnetGateway` value
* changed templates accordingly (also fixed few outdated templates with SubnetSize)
* docs updated
> add subnet gateway configuration

- hostmgr/cluster.go
It's kinda annoying when each time `mayu` is doing caching of host inventory  to see completely non-important log messages like:
```
Jul 28 19:51:43 000044c6d0e7cf0e docker[5014]: I0728 19:51:43.497824       1 cluster.go:433] file '/var/lib/mayu/images/conf.json' doesn't exist, skipping directory 'images'
Jul 28 19:51:43 000044c6d0e7cf0e docker[5014]: I0728 19:51:43.497842       1 cluster.go:433] file '/var/lib/mayu/templates/conf.json' doesn't exist, skipping directory 'templates'
Jul 28 19:51:43 000044c6d0e7cf0e docker[5014]: I0728 19:51:43.497848       1 cluster.go:433] file '/var/lib/mayu/yochu/conf.json' doesn't exist, skipping directory 'yochu'
```
I thnik it's not very usefull so moving this log to bigger verbosity level is fine.
> increase verbosity on nonexsiting host file

- main.go
- pxemgr/ipxe_handlers.go
If these errors are not checked a `template.Execute` call can fail and still write a valid (but incomplete) yaml without further notice.
> check template execution errors

- pxemgr/ipxe_handlers.go
- pxemgr/pxemanager_test.go
Closes: #112
Now the logs on template errors will look like:
```
I0821 13:13:02.528079       1 ipxe_handlers.go:252] generating a final stage cloudConfig
I0821 13:13:02.528101       1 cloudconfig.go:38] templates: [./templates/last_stage_cloudconfig.yaml template_snippets/cloudconfig/g8s_master.yaml template_snippets/cloudconfig/g8s_worker.yaml template_snippets/cloudconfig/net_bond.yaml template_snippets/cloudconfig/net_bridge.yaml template_snippets/cloudconfig/net_singlenic.yaml template_snippets/cloudconfig/net_singlevlan.yaml template_snippets/cloudconfig/nfs.yaml template_snippets/cloudconfig/quobyte.yaml template_snippets/cloudconfig/rook.yaml]
I0821 13:13:02.529806       1 ipxe_handlers.go:254] generating final stage cloudConfig failed: template: last_stage_cloudconfig.yaml:246:5: …
```
> prevent multiple http headers on template generation error

- pxemgr/ipxe_handlers.go
Added missing check for `WriteTo` error, according to https://golang.org/src/bytes/buffer.go?s=7059:7117#L198 there's a case when it can be different from the error returned by `w.Write`, maybe worth checking for all those too.
> check for WriteTo error

- flag.go
- main.go
- pxemgr/ipxe_handlers.go
- pxemgr/pxemanager.go
add coreos.autologin debug option flag to mayu
When  machine doesn't want to properly join cluster it's handy to have the option to enable `coreos.autologin` so that os will boot into logged console and you can check what is wrong
Should be used only for testing, it's not for production as its security risk.
> add coreos.autologin debug option

- pxemgr/ipxe_handlers.go
Unfortunately ipxe doesn't properly parse Vmware serial and it its  unusable for our case so we need to switch to uuid for machine identification.
> vmware serial fix

- scripts/fetch-flatcar-image
This adds a configurable option passed in to have CP nodes running a Flatcar version from a different channel
I'm not sure about the interface of this script. It accept a parameter `<path-to-store-image>` but it is not used anyhow in the script.
> Support configurable Flatcar channel

- go.mod
- go.sum
- hostmgr/cluster.go
- pxemgr/etcd_discovery_handlers.go
- templates/ignition.yaml
Trying to make the templating of https://github.com/giantswarm/mayu/pull/153 a little clearer. Also fixed the build by specifying the minimum TLS version (gosec) and running `go mod tidy`. I haven't tested this, but I figure we can merge it and test it on the `add-installation-proxy-config` branch if it looks alright.
> proxy config cleanup

- pxemgr/filemanager.go
- pxemgr/ignition.go
- pxemgr/pxemanager_test.go
`join` is a `helm` thing I mistakenly assumed existed in go templates. I'm defining the function so go can use it. I also updated the test so we can see the ignition output.
Example output from the test:
```json
{
"ignition": {
"config": {},
"security": {
"tls": {}
},
"timeouts": {},
"version": "2.2.0"
},
"networkd": {},
"passwd": {},
"storage": {},
"systemd": {
"units": [
{
"enabled": false,
"mask": true,
"name": "update-engine.service"
},
{
"dropins": [
{
"contents": "[Service]\nEnvironment=\"HTTP_PROXY=http://username:password@uri:123\"\nEnvironment=\"HTTPS_PROXY=http://username:password@uri:123\"\nEnvironment=\"NO_PROXY=example.com,other.example.com\"\n",
"name": "40-docker.conf"
}
],
"name": "docker.service"
}
]
}
}
```
> Add join function to ignition template context

- CHANGELOG.md
- flag.go
- main.go
- pxemgr/ipxe_handlers.go
- pxemgr/pxemanager.go
Current Mayu still has an old flag for the `autologin` and also some boot flags like `coreos.first_boot=1`
I need this because I've tried to run Flatcar 2247.6.0 (presumably the version corresponding to CoreOS not having any CPU fix) but Mayu has old unsupported flags.
The reason why I need the autologin is because when I start 2247.6.0 on the CP the nodes do not boot and get into emergency state and from VMware console I cannot login so I need to force the login having `autologin` in place.
> Change flags to flatcar
